server:
  port: 8080

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**

